cluster_upgrade_to_image: new role
openshift-psap/ci-artifacts pull request #107
Opened 2021-04-09 07:52 UTC by kpouget

This PR adds a new role for triggering an upgrade of OpenShift to a given image.
At the moment, no check is performed against the target image, and the upgrade is forced.

An upgrade hook is added to the CI entrypoint: `run cluster-upgrade`, which expects to receive the target image with `CLUSTER_UPGRADE_TARGET_IMAGE` environment variable.

The CI configuration is being updated with this PR https://github.com/openshift/release/pull/17498
It will remain as a presubmit hook until the GPU Operator supports cluster upgrade without uninstalling the operator.

2021-04-09 08:04 UTC, kpouget commented
/approve

On Fri, Apr 9, 2021 at 9:52 AM OpenShift CI Robot ***@***.***>
wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by:
> To complete the pull request process
> <https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process>,
> please ask for approval from *kpouget* after the PR has been reviewed.
>
> The full list of commands accepted by this bot can be found here
> <https://go.k8s.io/bot-commands?repo=openshift-psap%2Fci-artifacts>.
> Needs approval from an approver in each of these files:
>
>    - *OWNERS
>    <https://github.com/openshift-psap/ci-artifacts/blob/master/OWNERS>*
>
> Approvers can indicate their approval by writing /approve in a comment
> Approvers can cancel approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift-psap/ci-artifacts/pull/107#issuecomment-816491710>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZVQIRU3VNEVOIIK6ZINQDTH2W4XANCNFSM42UOR2GA>
> .
>

2021-04-13 21:36 UTC, ArangoGutierrez requested changes
looks good just some nits

2021-04-13 21:36 UTC, ArangoGutierrez commented on roles/cluster_upgrade_to_image/tasks/main.yml
> +- name: Check thatcluster_upgrade_image  is defined
```suggestion
- name: Check that cluster_upgrade_image  is defined
```

2021-04-13 21:36 UTC, ArangoGutierrez commented on roles/cluster_upgrade_to_image/tasks/main.yml
> +  fail: msg="Bailing out. This play requires 'cluster_upgrade_image'"
```suggestion
  fail: msg="Bailing out. This play requires 'cluster_upgrade_image' to be defined"
```

2021-04-14 06:28 UTC, kpouget commented
@ArangoGutierrez thanks for the review, I fixed and squashed the modifications

2021-04-14 06:28 UTC, kpouget commented
/test gpu-operator-e2e

2021-04-14 08:12 UTC, kpouget commented
/retest

On Wed, Apr 14, 2021 at 10:00 AM openshift-ci[bot] ***@***.***>
wrote:

> @kpouget <https://github.com/kpouget>: The following test *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> ci/prow/gpu-operator-e2e d6c9671
> <https://github.com/openshift-psap/ci-artifacts/commit/d6c967102b9ee8c41c12bea554e2dab11cda47b9>
> link
> <https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/107/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1382219197685174272> /test
> gpu-operator-e2e
>
> Full PR test history
> <https://prow.ci.openshift.org/pr-history?org=openshift-psap&repo=ci-artifacts&pr=107>.
> Your PR dashboard
> <https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kpouget>.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift-psap/ci-artifacts/pull/107#issuecomment-819316272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZVQIQO7PMPXS3GKDQIRTLTIVDSFANCNFSM42UOR2GA>
> .
>

2021-04-14 10:34 UTC, kpouget commented
/retest

On Wed, Apr 14, 2021 at 12:02 PM openshift-ci[bot] ***@***.***>
wrote:

> @kpouget <https://github.com/kpouget>: The following test *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> ci/prow/gpu-operator-e2e d6c9671
> <https://github.com/openshift-psap/ci-artifacts/commit/d6c967102b9ee8c41c12bea554e2dab11cda47b9>
> link
> <https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/107/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1382245486458572800> /test
> gpu-operator-e2e
>
> Full PR test history
> <https://prow.ci.openshift.org/pr-history?org=openshift-psap&repo=ci-artifacts&pr=107>.
> Your PR dashboard
> <https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kpouget>.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift-psap/ci-artifacts/pull/107#issuecomment-819397144>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZVQIXFMMZIYVEFFYEG7X3TIVR2ZANCNFSM42UOR2GA>
> .
>

2021-04-14 15:01 UTC, kpouget commented
/retest

2021-04-14 17:04 UTC, ArangoGutierrez approved these changes
/lgtm

2021-04-14 17:04 UTC, merged

2021-04-29 15:33 UTC, kpouget commented
Part of https://github.com/openshift-psap/ci-artifacts/issues/105